<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Features_logo-desktop</name>
   <tag></tag>
   <elementGuidId>b8f6ff69-95e5-473a-87d8-c5f0b4d5b33d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Eklipse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo-desktop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>43c6f3fb-45aa-499d-a3cc-ab4a89f45315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-desktop</value>
      <webElementGuid>87706d6f-730f-41e5-8ee1-cbf6e177cac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/09/logo_white.png?fit=251%2C50&amp;ssl=1</value>
      <webElementGuid>c0b2129f-7c3e-4c05-b632-a1100dc4541a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Eklipse</value>
      <webElementGuid>638841b3-6b71-4cc1-8b6f-2b9501472f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;page-template-default page page-id-14105 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-14105 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--left&quot;]/div[@class=&quot;header-main__logo&quot;]/a[1]/img[@class=&quot;logo-desktop&quot;]</value>
      <webElementGuid>4f014d23-ddd2-41ed-a07d-2ee3e828a3aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Eklipse']</value>
      <webElementGuid>76bffb77-9cfa-4261-b92e-daed2a275bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>60943cc6-eb74-40f8-97da-eefea8d0313e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/09/logo_white.png?fit=251%2C50&amp;ssl=1' and @alt = 'Eklipse']</value>
      <webElementGuid>9f9d5b89-541c-4224-8eb6-82f73e594bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
