<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AI EditNew</name>
   <tag></tag>
   <elementGuidId>4ab0283b-1365-492b-b2cf-374c422b8d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submenu-3 > ul > li > a.sidebar-submenu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='submenu-3']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc07a291-7f43-41bb-bed9-9ef96f3a2f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-submenu-link</value>
      <webElementGuid>ded2ed99-45d3-477f-b0aa-579e453a2a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edited-clip/ai-edit</value>
      <webElementGuid>a81fab96-246f-45d3-b46a-0a740adc5371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AI EditNew</value>
      <webElementGuid>c7185c51-aee8-4644-8070-56db8851b9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-3&quot;)/ul[1]/li[1]/a[@class=&quot;sidebar-submenu-link&quot;]</value>
      <webElementGuid>a2dff074-2ddc-4320-a6b0-6798ea946203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='submenu-3']/ul/li/a</value>
      <webElementGuid>9fb5c6f8-ee69-426b-93e7-870143b15696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edits'])[1]/following::a[1]</value>
      <webElementGuid>1f41f3af-33b7-4f45-a304-71e5e0d6eafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content Publisher'])[1]/following::a[2]</value>
      <webElementGuid>38f3641f-9c4a-4691-94ad-b2a3d5c38906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/edited-clip/ai-edit')]</value>
      <webElementGuid>565638cc-3232-45d4-afb4-b4af83e6d290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/ul/li/a</value>
      <webElementGuid>2b56b1b1-e4bc-4c2a-932e-df862709f67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/edited-clip/ai-edit' and (text() = 'AI EditNew' or . = 'AI EditNew')]</value>
      <webElementGuid>75eea218-2b2b-4f35-8b1c-967fa9faeec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
