<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Start AI Edit</name>
   <tag></tag>
   <elementGuidId>b8d3bdec-a9e0-4bc2-9787-a55d736c0935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ek-primary-button.mb-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div/div/div/div[2]/div/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>126119d5-7bcb-49b3-97c4-f89d258cf696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ek-primary-button mb-4</value>
      <webElementGuid>af91b45c-6f02-48d5-9a1a-1e8cce6b5724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start AI Edit</value>
      <webElementGuid>710c722b-dd2d-46c8-ab4e-5032b42f2cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-streams ek-ai-edit&quot;]/div[2]/div[1]/div[@class=&quot;content&quot;]/div[@class=&quot;empty-clip-container&quot;]/div[@class=&quot;empty-clip-upper d-flex flex-column justify-content-center align-items-center p-4 mb-3 mt-2&quot;]/button[@class=&quot;ek-primary-button mb-4&quot;]</value>
      <webElementGuid>4f3cac38-cc42-4e40-b527-5094a63370ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/div[2]/div/div/div[2]/div/button</value>
      <webElementGuid>767bf3f4-0bf5-4858-ae08-3879bc0338d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beta'])[1]/following::button[1]</value>
      <webElementGuid>e156e2d6-b9e8-40b7-a03f-130e1ab5f2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/following::button[1]</value>
      <webElementGuid>cd0f1126-4c9a-4a03-94b4-9964f1d1595e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Player is loading.'])[1]/preceding::button[1]</value>
      <webElementGuid>a5403723-64f7-4b53-8d33-44c71a75c056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/button</value>
      <webElementGuid>58233df1-c4e6-4cd6-9379-c1017f23ef1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Start AI Edit' or . = 'Start AI Edit')]</value>
      <webElementGuid>6c002e04-0fcb-456c-91ea-b13d0ac87947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
